[workspace]
authors = ["pakiessling <pakiessling@ukaachen.de>"]
channels = ["conda-forge"]
name = "valis_align"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
openjdk = ">=25.0.2,<26"
python = ">=3.11,<3.12"
ipykernel = ">=7.3.0,<8"
maven = ">=3.9.16,<4"

[pypi-dependencies]
valis-wsi = ">=1.2.0, <2"
colour-science = "==0.4.4"
